services:
  rust-dev:
    build: .
    # Mount the current directory to /app in the container so changes are immediately available
    volumes:
      - .:/app
    # Keep the container running with an interactive shell
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"

